apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: openshift-build-example
resources:
- imagestream.yaml
- parent
- child

secretGenerator:
  - name: parent-webhook
    envs:
      - secrets/parent-webhook.env
  - name: child-webhook
    envs:
      - secrets/child-webhook.env

generatorOptions:
  disableNameSuffixHash: true
